apiVersion: v1
kind: ReplicationController
metadata:
  name: krud
spec:
  replicas: 1
  selector:
    app: krud
  template:
    metadata:
      labels:
        app: krud
    spec:
      containers:
      - name: krud
        image: quay.io/coreos/krud:latest
        env:
        - name: KRUD_CONTROLLER_NAME
          value: rc-name
